services:
  foxogram-api-dev:
    build:
      context: ./foxogram-api
    restart: always
    networks:
      - db_dev_network
      - minio_network
      - traefik
    labels:
      traefik.enable: true
      traefik.http.routers.foxogram-api-dev.rule: Host(`api.dev.foxogram.su`)
      traefik.http.routers.foxogram-api-dev.tls.certresolver: letsencrypt
      traefik.http.services.foxogram-api-dev.loadbalancer.server.port: 8080

networks:
  db_dev_network:
    external: true
  minio_network:
    external: true
  traefik:
    external: true
